apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: bankplatform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: bankplatform/discovery-server:1.0.0
          ports:
            - containerPort: 8761
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server-service
  namespace: bankplatform
spec:
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8761
