apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: bankplatform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: bankplatform/transaction-service:1.0.0
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/transaction_db"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: bankplatform-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bankplatform-secrets
                  key: POSTGRES_PASSWORD
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: bankplatform-config
                  key: EUREKA_URL
            - name: ACCOUNT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: bankplatform-config
                  key: ACCOUNT_SERVICE_URL
          readinessProbe:
            httpGet:
              path: /transactions/health
              port: 8084
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: bankplatform
spec:
  selector:
    app: transaction-service
  ports:
    - port: 8084
      targetPort: 8084
